### ISSUE TITLE
rekenregels versie2 sleutelsoorten 6xxx

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#19]
@Patrik.Oosterlynck@inbo.be

Ik zie steeds operator <= staan bij sleutelsoorten (bedekking en aantal). Moet >= voor ondergrens (van B: goede staat). Ik stel voor om de bovengrens van B weg te laten, gezien onderscheid tussen A en B er niet toe doet. En als je de bovengrens laat staan krijg je fouten.

Andere habitatgroepen heb ik nog niet nagekeken, maar misschien zelfde probleem daar?

**Comment by Patrikoosterlynck** [comment]
Toon, de ondergrens voor B staat er toch ook in volgens mij, maar misschien wordt die niet meegemigreerd. Zie in dit printscreentje bv.
![image](https://user-images.githubusercontent.com/40395174/42698172-6277eb98-86bd-11e8-8551-d6f75fdc9375.png)

**Comment by ToonHub** [comment]
De ondergrens zou toch >= 4 moeten zijn ipv <= 4

Gezien we geen onderscheid maken tussen A en B is het handig als de bovengrens van B wordt weggelaten

**Comment by Patrikoosterlynck** [comment]
Dat staat er toch ook Toon volgens mij in de printscreen: bij ondergrens
4 <= 'Resultaat van de opdracht'
Of geraak je er met deze manier van weergave misschien niet mee verder?

Die bovengrens weghalen is (erg) veel werk vrees ik, ik kan namelijk in het aanpassen van de brondatabank geen A, B of C weglaten (eens die ooit zijn ingevoerd moeten daar iets voor ingevoerd worden anders kan ik niet saven... wat wil zeggen dat al die criteria from scratch opnieuw moeten worden ingevoerd en dat gaat over gros van versie 2 criteria volgens mij)
Kan je even bekijken of het ook anders kan?

**Comment by ToonHub** [comment]
OK. Ik snap het. Dan worden ze verkeerd ingelezen in de rekenmodule (namelijk als  waarde <= 4)

**Comment by Patrikoosterlynck** [comment]
oke laat maar weten hoe hiermee verder. Best met Els opnemen dit, maar zoals gezegd niet zo evident om aan te passen in de brondatabank

**Comment by ToonHub** [comment]
OK. Els geeft het door aan Gert.
