### ISSUE TITLE
indicator aantal levensvormen 6230_hmo versie2

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#20]
momenteel slechts 1 voorwaarde voor deze indicator. Maar hoe te bepalen?

Is het haalbaar om voor elke levensvorm een soortenlijst te maken en een voorwaarde voor elke levensvorm aan te maken.

ook bij subtype hnk en hn

**Comment by Patrikoosterlynck** [comment]
oke moet ik bekijken op basis van wat er in Florabank zit
