### ISSUE TITLE
2 voorwaarden 'aantal heischrale sleutelsoorten' 6230_hnk versie2

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#21]
naam aanpassen naar 
-  aantal heischrale sleutelsoorten EU
- aantal heischrale sleutelsoorten aanvullend

**Comment by Patrikoosterlynck** [comment]
Euh ja oke heb ik gedaan maar er zijn geen EU of aanvullende lijsten nochtans. Heb je gewoon een naam gekozen om ze te onderscheiden?
