### ISSUE TITLE
6410 mo en ve versie3 aantal sleutelsoorten: iets mis met soortenlijst?

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#24]
voorwaarde 'bedekking sleutelsoorten' geeft bij  de berekening een correct resultaat, maar voorwaarde 'aantal sleutelsoorten' geeft waarde 0. Ik vermoed dat er iets mis is met soortenlijst.

**Comment by Patrikoosterlynck** [comment]
Alles lijkt oke in de db. Ik stuur door naar Els
