### ISSUE TITLE
dubbele spatie bij voorwaarde 'bedekking sleutelsoorten excl. pijpenstrootje' 6410 mo en ve versie3 en versie 2

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#26]
dubbele spatie tussen  bedekking en sleutelsooten. Zorgt er voor dat de voorwaarde niet aan de juiste analysevariabele wordt gekoppeld.

Ook 6410 ve eens nakijken.

**Comment by Patrikoosterlynck** [comment]
ok is aangepast

**Comment by ToonHub** [comment]
Bij versie 2 --> zelfde probleem

**Comment by Patrikoosterlynck** [comment]
ok aangepast in versie 2

**Comment by ToonHub** [comment]
OK
