### ISSUE TITLE
6120 versie3 soortenlijst sleutelsoorten klopt niet helemaal

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#30]
Bv. te schrappen: Cardaminopsis arenosa (L.) Hayek en Verbascum nigrum L.
toe te voegen: Herniaria glabra.
Maar best nog eens volledig nakijken

**Comment by Patrikoosterlynck** [comment]
oke inderdaad hele reeks wijzigingen doorgevoerd
nu ok
