### ISSUE TITLE
6230_hn versie2 berekening 'aantal levensvormen' en 'bedekking hoogopschietende soorten'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#31]
hoe berekenen we deze voorwaarden op basis van vegetatieopname? er hangen geen soortenlijsten aan deze voorwaarden.

**Comment by Patrikoosterlynck** [comment]
die zal ik vandaag niet meer opgelost krijgen vrees ik, hier is meer werk aan...

**Comment by ToonHub** [comment]
bedekking hoogopschietende soorten laten we weg
Tijdelijke oplossing: Patrik heeft voor alles soorten in vegetatieopnames van 6230 levensvormen aangeduid op basis waarvan aantal per plot kan berekend worden
