### ISSUE TITLE
twee indicatoren voor aantal sleutelsoorten 6230_hnk versie2

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#32]
Er is een indicator voor het totaal aantal sleutelsoorten en een aprte indicator voor aantal sleutelsoorten per groep. Momenteel zit het in de databank als 1 indicator en is het totaal aantal sleutelsoorten hier een voorwaarde onder. 

Totaal aantal sleutelsoorten moet aparte indicator worden en best ook andere naam bv. 'aantal sleutelsoorten totaal'. Andere indicator kan dan bv. ' aantal sleutelsoorten per groep' genoemd worden.

De groepen zijn dan de heischrale en de kalkminnende, toch?

**Comment by Patrikoosterlynck** [comment]
Zou in orde moeten zijn nu

**Comment by ToonHub** [comment]
OK
