### ISSUE TITLE
4030 versie3 voorwaarde aanwezigheid specifieke sleutelsoorten

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#34]
naam voorwaarde veranderen naar 'aanwezigheid struikheide' conform naamgeving in 2310

**Comment by Patrikoosterlynck** [comment]
ok aangepast

**Comment by ToonHub** [comment]
ook versie 2 aanpassen op dezelfde manier

**Comment by ToonHub** [comment]
OK
