### ISSUE TITLE
2310 versie 3 sleutelsoorten

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#35]
Struikheide verwijderen uit soortenlijst bij voorwaarde 'aantal sleutelsoorten' (in deze voorwaarde immers enkel sleutelsoorten exclusief struikheide)

**Comment by Patrikoosterlynck** [comment]
In de brondatabank zit Calluna niet dubbel. Enkel in de lijst aanwezigheid 'sleutelsoorten' en niet in de S_sleutelsoorten....
In de voorwaarde wordt enkel naar S_sleutelsoorten verwezen...
Mogelijk probleem van hierarchie van de lijsten (S_aanwezigheidstruikhei zit onder S_sleutelsoorten: Els?)

**Comment by ToonHub** [comment]
Bij 4030 versie 3 zit Struikheide niet bij 'aantal sleutelsoorten' (wat dus OK is)
Maar bij 4030 versie 2 zit Struikheide wel bij 'aantal sleutelsoorten (wat dus niet OK is)

Misschien kan je voor beide versies eens vergelijken hoe je ze hebt ingevoerd. Eventueel kan je zo ook wat het probleem is bij 2310 versie 3

**Comment by ToonHub** [comment]
voor 2310 versie3 is het nu OK

**Comment by ToonHub** [comment]
ook OK voor 4030 versie 2
