### ISSUE TITLE
7140 meso versie 3 dominantie van een soort

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#42]
hier moeten we de maximum bedekking van alle soorten behalve draadzegge bepalen

dat kan door als analysevariabele maxBedekkingExcl te nemen en (enkel) draadzegge in de soortenlijst op te nemen. Dan worden alle soorten behalve draadzegge geselecteerd en de maximum bedekking berekend.

Om de analysevariabele te kunnen toekennen aan de voorwaarde moet de voorwaarde een andere naam krijgen omdat 'dominantie van een soort' al gekoppeld is aan maxBedekking (voor de berekening conform versie 2).

Dus:
- naam veranderen van voorwaarde, bv. 'dominantie van een soort excl. Draadzegge' (en dan kan ik die voorwaarde koppelen aan maxBedekkingExcl)
- soortenlijst met Draadzegge toevoegen aan voorwaarde

**Comment by ToonHub** [comment]
idem voor 6510_hu en b510_hus

- naam voorwaarde veranderen naar bv. 'dominantie van een soort excl. sleutelsoorten' (ik koppel die voorwaarde dan aan 'maxBedekkingExcl'
- sleutelsoorten toevoegen aan voorwaarde

**Comment by Patrikoosterlynck** [comment]
oke opnieuw aangepast (stond oorspronkelijk zo en was eens teruggezet op de 'dominantie van een soort')

**Comment by ToonHub** [comment]
bij 7140 meso versie 3 ontbreekt nog de soortenlijst (die enkel Draadzegge bevat)

**Comment by ToonHub** [comment]
OK
