### ISSUE TITLE
1330_hpr voorwaarde 'som bedekking grasachtigen uit het zilverschoonver'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#44]
naam is te lang en wordt daarom afgeknipt vermoed ik
naam mag wat beknopter --> bv. 'bedekking grasachtigen rbbzil'

bij versie 2 staat er 'ssom bedekking grasachtigen uit het zilverschoonve' --> 'bedekking grasachtigen rbbzil'

vergeet dan ook referentiewaarden niet mee aan te passen

**Comment by Patrikoosterlynck** [comment]
ok aangepast
