### ISSUE TITLE
4010 versie2: twee indicatoren met naam 'veenmossen'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#45]
Binnen bepaald Habitattype/versie graag steeds verschillende naam voor de indicatoren. Anders wordt het verwarrend in de analyse.

In dit geval bv.: 'veenmossen' voor 'aantal veenmossen' en 'veenmoslaag' voor 'bedekking veenmoslaag'

**Comment by Patrikoosterlynck** [comment]
ok aangepast naar veenmoslaag en aantal veenmossen
