### ISSUE TITLE
2310 en 4030  voorwaarde 'aantal ouderdomsstadia'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#48]
Bij versie 2 gaat het om aantal ouderdomsstadia bij versie 3 om aantal talrijke ouderdomsstadia. Maar de voorwaarde heeft dezelfde naam in beide versies: 'aantal ouderdomsstadia'. De rekenmodule kan dus geen onderscheid maken.

Daarom naam veranderen bij 2310 en 4030 Versie 3: 'aantal ouderdomsstadia' --> 'aantal talrijke ouderdomsstadia'

**Comment by Patrikoosterlynck** [comment]
oke aangepast

**Comment by ToonHub** [comment]
OK
