### ISSUE TITLE
combinatie sleutelsoorten van de kruidlaag voor boshabitats versie 3 niet OK

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#49]
nu staat er: 'bekking' OF ('aantal' EN 'aandeel')

maar moet zijn:  'aantal' EN ('bedekking' OF 'aandeel)

**Comment by Patrikoosterlynck** [comment]
hier ben ik wat dingen aan het proberen zal ten vroegste donderdag opgelost zijn vrees ik

**Comment by ToonHub** [comment]
is OK
