### ISSUE TITLE
sleutelsoorten kruidlaag bossen versie2

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#50]
Bij Versie 2 van de boshabitats gaat het steeds om het aandeel sleutelsoorten in de kruidlaag en niet de absolute bedekking van de sleutelsoorten

Dus: de voorwaarden 'bedekking sleutelsoorten kruidlaag' veranderen naar 'aandeel sleutelsoorten kruidlaag'. Dan wordt die voorwaarde op de correcte manier berekend.

**Comment by Patrikoosterlynck** [comment]
ok aangepast, maar wel pas savonds dus mogelijk pas vanaf vrijdag gemigreerd

**Comment by ToonHub** [comment]
ok
