### ISSUE TITLE
9190 versie 3 'bedekking verruiging totaal'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#51]
Soortenlijst bevat o.a. Pijpenstrootje en Bochtige smele. Moet eruit.

Ook bij andere habitattypen best eens nakijken.

**Comment by Patrikoosterlynck** [comment]
oke doorgevoerd

**Comment by Patrikoosterlynck** [comment]
Zal ook wat vertraging opzitten wat soortaanpassingen moet Els, manueel nog een extra bewerking doen

**Comment by ToonHub** [comment]
OK
