### ISSUE TITLE
91E0_vc versie 3 'bedekking verruiging sublijst 1'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#52]
er zijn twee voorwaarden 'bedekking verruiging sublijst 1' eentje met grenswaarde <= 10 en eentje met grenswaarde >= 10. Deze laatste moet weg.

**Comment by Patrikoosterlynck** [comment]
oke aangepast, maar mogelijk pas vanaf vrijdag naar databank gemigreerd

**Comment by ToonHub** [comment]
OK
