### ISSUE TITLE
voorwaarden verruiging versie 3 maximum bedekking

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#54]
Voor sommige sublijstjes van verruiging geldt dat de maximale bedekking van de soorten niet hoger mag zijn dan de referentiewaarde. Momenteel wordt steeds de gezamenlijke bedekking berekend.
Om dit aan te passen moet je voorwaardenaam veranderen en dan kan ik daar de juiste analysevariabele aankoppelen.

Er zijn twee gevallen waar dit moet aangepast worden:
91E0_vo: 'bedekking verruiging sublijst 4' --> 'maximum bedekking verruiging sublijst 4'
91E0_vc: 'bedekking verruiging sublijst 2' --> 'maximum bedekking verruiging sublijst 2'

**Comment by Patrikoosterlynck** [comment]
ok aangepast, kbegrijp wel niet goed waarom enkel deze twee aanpassingen en niet meer van de verruigingsvoorwaarden...

**Comment by ToonHub** [comment]
Bij deze twee gevallen staat dat 'elk' van de soorten niet hoger mag zijn dan de referentiewaarde. In de andere gevallen staat er dat de soorten 'samen' niet hoger mogen zijn dan de referentiewaarde.
