### ISSUE TITLE
1330 zk en pol, versie 2 en 3: aandeel sleutelsoorten in de begroeide oppervlakte

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#55]
- Type variabele veranderen naar Percentage

- Kan dit geïnterpreteerd worden als aandeel sleutelsoorten in de kruidlaag? Zo ja Kruidlaag toevoegen als studiewaarde. Of is het aandeel t.o.v. gezamenlijke bedekking kruid- struik- en boomlaag. In dat geval alle vegetatielagen toevoegen als studiewaarde.

**Comment by Patrikoosterlynck** [comment]
Is dit de eerste keer dat je een soortenlijst relatief tov een vegetatielaag dient te berekenen?
Ik heb hiervoor namelijk niet onmiddellijk een oplossing. Ik kan in de databank geen Soortenlijst samen met een studiewaarde invoeren. 

Idem voor onderscheid decimaal en percentage dat wordt niet op het niveau van de invoerdatabank vastgelegd.

Ik vraag na bij Els om de aanpassing te doen

**Comment by ToonHub** [comment]
Bij de bossen komt dit ook voor (aandeel sleutelsoorten kruidlaag) en dat werkt daar.

**Comment by Patrikoosterlynck** [comment]
Ja zag ik ook maar ik zie daar geen specifieke invoersettings voor... ik wacht even op Els

**Comment by ToonHub** [comment]
Heb dit aangepast is in orde nu
