### ISSUE TITLE
1330_da, 1320 en 1310_zk versie 3: aanwezigheid schorklif/breuksteenbestorting

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#56]
Typevariabelen veranderen van Categorie naar Ja/nee

**Comment by Patrikoosterlynck** [comment]
Momenteel zit deze ind erin als twee gecombineerde voorwaarden (een J/N AND mate van voorkomen in bedekking. Wil je dat ik ze dus aanpas naar één J/N voorwaarde?

**Comment by ToonHub** [comment]
Ah ok. Zit er nu in als bedekking. Je moet het niet aanpassen.
