### ISSUE TITLE
1330_da versie3 indicator 'schorklif/breuksteenbestorting'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#57]
indicator zit momenteel op volgende manier in databank:

 'schorklif/breuksteenbestorting' <= weinig talrijk EN 'habitattype lager dan het klif' = 1

maar moet zijn:  
'schorklif/breuksteenbestorting' <= weinig talrijk OF (  'schorklif/breuksteenbestorting' >  weinig talrijk EN 'habitattype lager dan het klif' = 1)

zie tekst uit LSVI hieronder:
schorklif/breuksteenbestorting hooguit weinig talrijk aanwezig: lage schorvegetaties blijven in stand of breiden uit
OF: schorklif meer dan weinig talrijk aanwezig met de lage schorvegetatie voor (= lager dan) het klif
te bepalen op niveau van een aaneengesloten slikken-schorrengebied

**Comment by Patrikoosterlynck** [comment]
Heb ik opgelost 
zou morgen oke moeten zijn

**Comment by ToonHub** [comment]
Combinatie voorwaarden is OK nu.

Maar grenswaarde zou nog aangepast moeten worden (zie mail Bart) naar 15%.

Het zou ook logischer zijn als de voorwaardenaam wordt aangepast:

'aanwezigheid schorklif/breuksteenbestorting' --> 'aandeel schorklif/breuksteenbestorting'

**Comment by ToonHub** [comment]
OK nu
