### ISSUE TITLE
indicator verbossing 2160 versie3

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#58]
Er zitten twee voorwaarden in, waarvan een met referentiewaarde >= 5 --> die moet verwijderd worden.
De juiste voorwaarde is dus die met referentiewaarde <=10. Maar bij deze voorwaarde mag enkel de boomlaag meegerekend worden voor verbossing, want je zit daar met struweeltoestanden.  Kan jij dat aanpassen?

**Comment by Patrikoosterlynck** [comment]
Die referentiewaarde is aangepast, tweede deel van probleem is wat lastiger en moet ik via Gert passeren met een aangepaste query vermoed ik... ik hou je op de hoogte

**Comment by ToonHub** [comment]
Is in orde
