### ISSUE TITLE
1330_da versie 2 referentiewaarde voorwaarde 'aanwezigheid schorklifvorming'

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#61]
referentiewaarde staat nu op = 1: dus aanwezig. Maar zou <= 1 moeten zijn, want het zou ook in voldoende staat moeten zijn als het afwezig is.

**Comment by ToonHub** [comment]
Dit is niet aangepast in de databank. Best deze voorwaarde gewoon weglaten.

**Comment by Patrikoosterlynck** [comment]
vreemd staat nochtans aangepast
heb ze nu verwijderd

**Comment by ToonHub** [comment]
Sorry. Nog eens in detail bekeken. En zou er zo moeten uitzien.
'Aanwezigheid schorklifvorming' = 0 OF 'schorklifvegetaties aanwezig' = 1

Kan je die voorwaarde nog terughalen of is die verdwenen?

**Comment by Patrikoosterlynck** [comment]
OK no prob
heb die er terug ingezet als:
'aanwezigheid schorklifvorming'=Nee OR 'schorklifvegetaties aanwezig' = Ja

of heb je liever die hoofdletter bij 'Aanwezigheid schorklifvorming'?

**Comment by ToonHub** [comment]
nee t is goed zo. Bedankt!

**Comment by ToonHub** [comment]
Is in orde nu.
