### ISSUE TITLE
2110

### ISSUE THREAD

**Issue by ToonHub** [ToonHub/RapportageHabitats#64]
- voorwaarde 'menselijke structuren aanwezig' (Versie 3) heeft als type 'decimaal getal', maar moet 'ja/nee' zijn. Kan jij dat aanpassen?
- voorwaarde 'oppervlakte in m²' (Versie 2) heeft als type 'geheel getal', maar moet decimaal getal zijn. Kan je dat aanpassen? (In versie 3 staat dat wel goed)

**Comment by Patrikoosterlynck** [comment]
ok heb ik zonet gedaan

**Comment by ToonHub** [comment]
OK
